export const queryKeys = {
  me: ["me"] as const,
  setupStatus: ["setup", "status"] as const,
  settings: ["settings"] as const,
  users: ["users"] as const,
  user: (id: string) => ["users", id] as const,
  groups: ["groups"] as const,
  group: (id: string) => ["groups", id] as const,
  permissions: (resourceType: number, resourceId: string) => ["permissions", resourceType, resourceId] as const,
  folderTree: ["folders", "tree"] as const,
  document: (id: string) => ["documents", id] as const,
  documentVersions: (id: string) => ["documents", id, "versions"] as const,
  documentVersion: (id: string, versionId: string) => ["documents", id, "versions", versionId] as const,
  documentExport: (id: string) => ["documents", id, "export"] as const,
  search: (query: string, page: number, tagId?: string) => ["search", query, page, tagId ?? null] as const,
  tags: ["tags"] as const,
  auditLogs: (filter: Record<string, unknown>) => ["audit", filter] as const,
  images: (limit: number) => ["assets", "images", limit] as const,
};
